// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: grpc/grpc.proto

package grpc_util

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PutLog_PutOperation_FullMethodName = "/grpc_util.PutLog/PutOperation"
)

// PutLogClient is the client API for PutLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PutLogClient interface {
	PutOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Status, error)
}

type putLogClient struct {
	cc grpc.ClientConnInterface
}

func NewPutLogClient(cc grpc.ClientConnInterface) PutLogClient {
	return &putLogClient{cc}
}

func (c *putLogClient) PutOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PutLog_PutOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PutLogServer is the server API for PutLog service.
// All implementations must embed UnimplementedPutLogServer
// for forward compatibility.
type PutLogServer interface {
	PutOperation(context.Context, *Operation) (*Status, error)
	mustEmbedUnimplementedPutLogServer()
}

// UnimplementedPutLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPutLogServer struct{}

func (UnimplementedPutLogServer) PutOperation(context.Context, *Operation) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method PutOperation not implemented")
}
func (UnimplementedPutLogServer) mustEmbedUnimplementedPutLogServer() {}
func (UnimplementedPutLogServer) testEmbeddedByValue()                {}

// UnsafePutLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PutLogServer will
// result in compilation errors.
type UnsafePutLogServer interface {
	mustEmbedUnimplementedPutLogServer()
}

func RegisterPutLogServer(s grpc.ServiceRegistrar, srv PutLogServer) {
	// If the following call panics, it indicates UnimplementedPutLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PutLog_ServiceDesc, srv)
}

func _PutLog_PutOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PutLogServer).PutOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PutLog_PutOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PutLogServer).PutOperation(ctx, req.(*Operation))
	}
	return interceptor(ctx, in, info, handler)
}

// PutLog_ServiceDesc is the grpc.ServiceDesc for PutLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PutLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_util.PutLog",
	HandlerType: (*PutLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutOperation",
			Handler:    _PutLog_PutOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc.proto",
}
